// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MNKR_SAN_MapGenerator","status":true,"description":"v1.2.0 自動的にランダムマップを生成します。","parameters":{"WallHight":"1","MinRoomSize":"5","MaxRoomSize":"10","ShowOuterWall":"true"}}
];
